export const mockAppointments = [
  {
    id: 'APT-001',
    patientName: 'Nguyễn Minh Anh',
    patientPhone: '0901 234 567',
    specialty: 'Tim mạch',
    doctorName: 'Dr. Trần Quốc Huy',
    appointmentDate: '2026-06-03',
    appointmentTime: '08:30',
    status: 'WAITING_CHECK_IN',
    paymentStatus: 'UNPAID',
    bookingType: 'ONLINE',
    note: 'Bệnh nhân đặt lịch khám đau ngực nhẹ.',
  },
  {
    id: 'APT-002',
    patientName: 'Lê Thị Hoài',
    patientPhone: '0912 888 456',
    specialty: 'Tai Mũi Họng',
    doctorName: 'Dr. Phạm Ngọc Lan',
    appointmentDate: '2026-06-03',
    appointmentTime: '09:00',
    status: 'CHECKED_IN',
    paymentStatus: 'PAID',
    bookingType: 'ONLINE',
    note: 'Khám viêm họng kéo dài.',
  },
  {
    id: 'APT-003',
    patientName: 'Trần Văn Nam',
    patientPhone: '0987 654 321',
    specialty: 'Nội tổng quát',
    doctorName: 'Dr. Nguyễn Thanh Bình',
    appointmentDate: '2026-06-03',
    appointmentTime: '09:30',
    status: 'WAITING_PAYMENT',
    paymentStatus: 'UNPAID',
    bookingType: 'ONLINE',
    note: 'Khám sức khỏe tổng quát.',
  },
  {
    id: 'APT-004',
    patientName: 'Phạm Gia Bảo',
    patientPhone: '0933 222 111',
    specialty: 'Da liễu',
    doctorName: 'Dr. Đỗ Mai Chi',
    appointmentDate: '2026-06-03',
    appointmentTime: '10:00',
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    bookingType: 'WALK_IN',
    note: 'Bệnh nhân đến trực tiếp tại quầy.',
  },
  {
    id: 'APT-005',
    patientName: 'Vũ Khánh Linh',
    patientPhone: '0966 456 789',
    specialty: 'Nhi khoa',
    doctorName: 'Dr. Hoàng Minh Đức',
    appointmentDate: '2026-06-04',
    appointmentTime: '14:00',
    status: 'CANCELLED',
    paymentStatus: 'REFUNDED',
    bookingType: 'ONLINE',
    note: 'Bệnh nhân đã hủy lịch trước giờ khám.',
  },
  {
    id: 'APT-006',
    patientName: 'Đặng Hữu Phúc',
    patientPhone: '0977 111 999',
    specialty: 'Chấn thương chỉnh hình',
    doctorName: 'Dr. Bùi Anh Tuấn',
    appointmentDate: '2026-06-04',
    appointmentTime: '15:30',
    status: 'NO_SHOW',
    paymentStatus: 'UNPAID',
    bookingType: 'ONLINE',
    note: 'Không đến khám theo lịch hẹn.',
  },
];

export const appointmentStatuses = [
  { value: 'ALL', label: 'Tất cả trạng thái' },
  { value: 'WAITING_CHECK_IN', label: 'Chờ check-in' },
  { value: 'WAITING_PAYMENT', label: 'Chờ thanh toán' },
  { value: 'CHECKED_IN', label: 'Đã check-in' },
  { value: 'COMPLETED', label: 'Hoàn thành' },
  { value: 'CANCELLED', label: 'Đã hủy' },
  { value: 'NO_SHOW', label: 'Không đến khám' },
];

export const paymentStatuses = [
  { value: 'ALL', label: 'Tất cả thanh toán' },
  { value: 'UNPAID', label: 'Chưa thanh toán' },
  { value: 'PAID', label: 'Đã thanh toán' },
  { value: 'REFUNDED', label: 'Đã hoàn tiền' },
];
