server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/mass_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Secret
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=he186017leducanh@gmail.com
spring.mail.password=elmu nope wtkh egcx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

payos.client-id=d35d97e2-befa-42a8-a098-8323bef9c236
payos.api-key=b1ab622a-43fd-4574-aafa-aa4eeaa3f424
payos.checksum-key=0c717f5e7574e3e907163e5064bb045b5d6719c8e6de2c8a31832a8310dcc32c

app.frontend.payment-success-url=http://localhost:5173/payment/success
app.frontend.payment-cancel-url=http://localhost:5173/payment/cancel
